# Generated by Django 6.1.1 on 2026-09-03 20:23

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accent_color",
            field=models.CharField(
                default=apps.accounts.models.default_accent_color,
                help_text="Your identity color across avatars and presence.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                blank=True, help_text="A short line about you.", max_length=280
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
