# Generated by Django 6.1.1 on 2026-09-20 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_accent_color_profile_bio_profile_pronouns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="timezone",
        ),
    ]
