# Generated by Django 6.1.1 on 2026-09-03 10:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partnerships", "0002_parternship_db_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whiteboard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partnership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard",
                        to="partnerships.partnership",
                    ),
                ),
            ],
            options={
                "verbose_name": "whiteboard",
                "verbose_name_plural": "whiteboards",
                "ordering": ["-created_at"],
            },
        ),
    ]
