# Generated by Django 6.1.1 on 2026-09-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partnerships", "0002_parternship_db_constraints"),
        ("whiteboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteboardOperation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_id", models.UUIDField(db_index=True)),
                ("sequence", models.PositiveBigIntegerField(editable=False)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create_stroke", "Create stroke"),
                            ("delete_object", "Delete object"),
                            ("clear_canvas", "Clear canvas"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("base_version", models.PositiveBigIntegerField(default=0, editable=False)),
                ("resulting_version", models.PositiveBigIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "whiteboard operation",
                "verbose_name_plural": "whiteboard operations",
                "ordering": ("sequence",),
            },
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="last_operation_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="title",
            field=models.CharField(blank=True, default="Shared board", max_length=120),
        ),
        migrations.AddField(
            model_name="whiteboard",
            name="version",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name="whiteboard",
            index=models.Index(fields=["status"], name="idx_wb_status"),
        ),
        migrations.AddField(
            model_name="whiteboardoperation",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whiteboard_operations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="whiteboardoperation",
            name="whiteboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="whiteboard.whiteboard",
            ),
        ),
        migrations.AddIndex(
            model_name="whiteboardoperation",
            index=models.Index(fields=["whiteboard", "sequence"], name="idx_op_board_seq"),
        ),
        migrations.AddIndex(
            model_name="whiteboardoperation",
            index=models.Index(fields=["whiteboard", "operation_type"], name="idx_op_board_type"),
        ),
        migrations.AddIndex(
            model_name="whiteboardoperation",
            index=models.Index(fields=["whiteboard", "created_at"], name="idx_op_board_created"),
        ),
        migrations.AddConstraint(
            model_name="whiteboardoperation",
            constraint=models.UniqueConstraint(
                fields=("whiteboard", "sequence"), name="uniq_op_sequence_per_board"
            ),
        ),
        migrations.AddConstraint(
            model_name="whiteboardoperation",
            constraint=models.UniqueConstraint(
                fields=("whiteboard", "operation_id"), name="uniq_op_id_per_board"
            ),
        ),
    ]
