# Generated by Django 6.1.1 on 2026-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whiteboard", "0002_whiteboardoperation_whiteboard_archived_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="whiteboardoperation",
            name="idx_op_board_seq",
        ),
        migrations.AlterField(
            model_name="whiteboard",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=16,
            ),
        ),
    ]
