# Generated by Django 6.1.1 on 2026-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whiteboard", "0003_remove_whiteboardoperation_idx_op_board_seq_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whiteboardoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("create_stroke", "Create stroke"),
                    ("delete_object", "Delete object"),
                    ("clear_canvas", "Clear canvas"),
                    ("move_object", "Move object"),
                    ("resize_object", "Resize object"),
                    ("restore_version", "Restore version"),
                ],
                max_length=32,
            ),
        ),
    ]
