# Generated by Django 6.1.1 on 2026-09-03 07:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "partnership",
                "verbose_name_plural": "partnerships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("invitation_created", "Invitation created"),
                            ("invitation_resent", "Invitation resent"),
                            ("invitation_revoked", "Invitation revoked"),
                            ("invitation_accepted", "Invitation accepted"),
                            ("invitation_rejected", "Invitation rejected"),
                            ("invitation_expired", "Invitation expired"),
                            ("invitation_invalid", "Invitation invalid"),
                            ("partnership_activated", "Partnership activated"),
                            ("partnership_ended", "Partnership ended"),
                            ("partnership_cancelled", "Partnership cancelled"),
                            ("member_left", "Member left"),
                            ("member_removed", "Member removed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="partnerships.partnership",
                    ),
                ),
            ],
            options={
                "verbose_name": "partnership event",
                "verbose_name_plural": "partnership events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("text", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "is_read"], name="idx_notif_recip_read")
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnershipInvitation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("invitee_email", models.EmailField(db_index=True, max_length=254)),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partnership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="partnerships.partnership",
                    ),
                ),
            ],
            options={
                "verbose_name": "partnership invitation",
                "verbose_name_plural": "partnership invitations",
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="idx_inv_status_expiry"),
                    models.Index(fields=["invitee", "status"], name="idx_inv_invitee_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "sent")),
                        fields=("inviter", "invitee_email"),
                        name="uniq_app_one_active_sent_inviter_email",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "sent")),
                        fields=("partnership", "invitee_email"),
                        name="uniq_app_one_active_partnership_email",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnershipMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left"), ("removed", "Removed")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partnership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="partnerships.partnership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "partnership member",
                "verbose_name_plural": "partnership members",
                "indexes": [
                    models.Index(fields=["partnership", "status"], name="idx_member_part_status"),
                    models.Index(fields=["user", "status"], name="idx_member_user_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partnership", "user"), name="uniq_member_per_partnership"
                    )
                ],
            },
        ),
    ]
